name: smartbat_bms
description: SmartBat LiFePO4 Battery BMS Monitor
version: 1.2.1+4

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.0
  fl_chart: ^0.69.0
  path_provider: ^2.1.0
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Odin_Kopf.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/Odin_Kopf.png
  adaptive_icon_foreground: assets/Odin_Kopf.png
  adaptive_icon_monochrome: assets/Odin_Kopf.png
  adaptive_icon_background: "#111111"
  adaptive_icon_foreground_inset: 16
  min_sdk_android: 21
